name: MigrationSample.Legacy.CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Restore packages
      run: nuget restore migrationsample.sln
    - name: Build with MSBuild
      run: msbuild  migrationsample.sln -p:Configuration=Release
